# Generated by Django 5.0.7 on 2024-08-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionsAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("1", "Value One"),
                            ("2", "Value Two"),
                            ("3", "Value Three"),
                            ("4", "Value Four"),
                            ("5", "Value Five"),
                            ("6", "Value Six"),
                            ("7", "Value Seven"),
                            ("8", "Value Eight"),
                            ("9", "Value Nine"),
                            ("10", "Value Ten"),
                        ],
                        default="valueOne",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BehavioursAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("1", "Value One"),
                            ("2", "Value Two"),
                            ("3", "Value Three"),
                            ("4", "Value Four"),
                            ("5", "Value Five"),
                            ("6", "Value Six"),
                            ("7", "Value Seven"),
                            ("8", "Value Eight"),
                            ("9", "Value Nine"),
                            ("10", "Value Ten"),
                        ],
                        default="valueOne",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeelingsAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("1", "Value One"),
                            ("2", "Value Two"),
                            ("3", "Value Three"),
                            ("4", "Value Four"),
                            ("5", "Value Five"),
                            ("6", "Value Six"),
                            ("7", "Value Seven"),
                            ("8", "Value Eight"),
                            ("9", "Value Nine"),
                            ("10", "Value Ten"),
                        ],
                        default="valueOne",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PresenceAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("1", "Value One"),
                            ("2", "Value Two"),
                            ("3", "Value Three"),
                            ("4", "Value Four"),
                            ("5", "Value Five"),
                            ("6", "Value Six"),
                            ("7", "Value Seven"),
                            ("8", "Value Eight"),
                            ("9", "Value Nine"),
                            ("10", "Value Ten"),
                        ],
                        default="valueOne",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThoughtsAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("1", "Value One"),
                            ("2", "Value Two"),
                            ("3", "Value Three"),
                            ("4", "Value Four"),
                            ("5", "Value Five"),
                            ("6", "Value Six"),
                            ("7", "Value Seven"),
                            ("8", "Value Eight"),
                            ("9", "Value Nine"),
                            ("10", "Value Ten"),
                        ],
                        default="valueOne",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
