# Generated by Django 5.0.7 on 2024-08-09 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionsassessment",
            name="form_submission_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="behavioursassessment",
            name="form_submission_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="feelingsassessment",
            name="form_submission_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="presenceassessment",
            name="form_submission_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="thoughtsassessment",
            name="form_submission_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="actionsassessment",
            name="choice",
            field=models.CharField(
                choices=[
                    ("1", "Value One"),
                    ("2", "Value Two"),
                    ("3", "Value Three"),
                    ("4", "Value Four"),
                    ("5", "Value Five"),
                    ("6", "Value Six"),
                    ("7", "Value Seven"),
                    ("8", "Value Eight"),
                    ("9", "Value Nine"),
                    ("10", "Value Ten"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="behavioursassessment",
            name="choice",
            field=models.CharField(
                choices=[
                    ("1", "Value One"),
                    ("2", "Value Two"),
                    ("3", "Value Three"),
                    ("4", "Value Four"),
                    ("5", "Value Five"),
                    ("6", "Value Six"),
                    ("7", "Value Seven"),
                    ("8", "Value Eight"),
                    ("9", "Value Nine"),
                    ("10", "Value Ten"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="feelingsassessment",
            name="choice",
            field=models.CharField(
                choices=[
                    ("1", "Value One"),
                    ("2", "Value Two"),
                    ("3", "Value Three"),
                    ("4", "Value Four"),
                    ("5", "Value Five"),
                    ("6", "Value Six"),
                    ("7", "Value Seven"),
                    ("8", "Value Eight"),
                    ("9", "Value Nine"),
                    ("10", "Value Ten"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="presenceassessment",
            name="choice",
            field=models.CharField(
                choices=[
                    ("1", "Value One"),
                    ("2", "Value Two"),
                    ("3", "Value Three"),
                    ("4", "Value Four"),
                    ("5", "Value Five"),
                    ("6", "Value Six"),
                    ("7", "Value Seven"),
                    ("8", "Value Eight"),
                    ("9", "Value Nine"),
                    ("10", "Value Ten"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="thoughtsassessment",
            name="choice",
            field=models.CharField(
                choices=[
                    ("1", "Value One"),
                    ("2", "Value Two"),
                    ("3", "Value Three"),
                    ("4", "Value Four"),
                    ("5", "Value Five"),
                    ("6", "Value Six"),
                    ("7", "Value Seven"),
                    ("8", "Value Eight"),
                    ("9", "Value Nine"),
                    ("10", "Value Ten"),
                ],
                default="1",
                max_length=10,
            ),
        ),
    ]
