# Generated by Django 5.0.7 on 2024-08-11 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_actionsassessment_form_submission_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FillInTheBlanksIntention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity", models.TextField(blank=True)),
                ("action", models.TextField(blank=True)),
                ("feeling", models.TextField(blank=True)),
                ("form_submission_date", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
