# Generated by Django 5.0.7 on 2024-08-20 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_fillintheblanksintention"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity", models.CharField(blank=True, default="", max_length=100)),
                ("action", models.TextField(blank=True, default="")),
                ("feeling", models.TextField(blank=True, default="")),
                ("form_submission_date", models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name="FillInTheBlanksIntention",
        ),
        migrations.AlterField(
            model_name="actionsassessment",
            name="choice",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                default="6",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="behavioursassessment",
            name="choice",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                default="6",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="feelingsassessment",
            name="choice",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                default="6",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="presenceassessment",
            name="choice",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                default="6",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="thoughtsassessment",
            name="choice",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                default="6",
                max_length=10,
            ),
        ),
    ]
