# Generated by Django 5.0.7 on 2024-08-21 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="form_submission_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
