# Generated by Django 5.0.7 on 2024-08-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_shift_form_submission_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="realigned_beliefs",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
