# Generated by Django 5.0.7 on 2024-08-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_shift_realigned_beliefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="presence_shift",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
