# Generated by Django 5.0.7 on 2024-08-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_shift_presence_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="decision_techniques",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
