# Generated by Django 5.0.7 on 2024-08-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_shift_decision_techniques"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="promises",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
