# Generated by Django 5.0.7 on 2024-08-22 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_decisionassessment"),
    ]

    operations = [
        migrations.CreateModel(
            name="NaturalnessAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ],
                        default="6",
                        max_length=10,
                    ),
                ),
                ("form_submission_date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
